name: dartiverse_ssh_client_cli
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: 3.1.0-94.0.dev

# Add regular dependencies here.
dependencies:
  dartssh2: ^2.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0